# Generated by Django 5.1 on 2024-09-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_appointment_requested_at_alter_appointment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service_type',
            field=models.CharField(choices=[('home', 'Home Service'), ('office', 'Office Visit')], default='office', max_length=20),
        ),
    ]
